# Generated by Django 2.1.4 on 2020-06-09 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0005_auto_20200609_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 12, 29, 43, 947140), verbose_name='date published'),
        ),
    ]
