# Generated by Django 2.1.4 on 2020-06-09 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0006_auto_20200609_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 12, 47, 1, 111853), verbose_name='date published'),
        ),
    ]
