# Generated by Django 2.1.4 on 2020-06-09 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0007_auto_20200609_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 13, 46, 3, 113976), verbose_name='date published'),
        ),
    ]
