# Generated by Django 2.1.4 on 2020-06-17 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0008_auto_20200609_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='img',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 12, 54, 1, 14835), verbose_name='date published'),
        ),
    ]
